##### CREATE AN ANNOTATED .FAM FILE TO BE USED WITH PLINK #####
### Argument 1: a .fam file, generated by plink
### Argument 2: and annotation file with the following format:
###   Status	ID 						Gender
###   Case		I-PAL_SPSY_000222_001   M
###   Control	I-PAL_SPSY_000222_002	F

### The script will directly transform M and F in the right format and also the Case/Control status
### !! Notice that this script re-write the existing .fam file (input), so the old file gets lost.
options(warn=-1)

# Read arguments #
args <- commandArgs(trailingOnly = TRUE)
infamD = as.character(args[1])
inannD = as.character(args[2])

#infamD =  "/humgen/atgu1/fs03/wip/aganna/fin_seq/processed/seq/G77318RH.fam"
#inannD =  "/humgen/atgu1/fs03/wip/aganna/fin_seq/original/seq/pheno_gender.txt"


infam <- read.table(infamD,header=F,stringsAsFactor=F)
infam$V1 <- gsub('/g','',infam$V1)
inann <- read.table(inannD,header=T,stringsAsFactor=F)
inann$gender <- ifelse(inann$gender=="F",2,1)
inann$status <- ifelse(inann$status=="Case",2,1)

print (paste0("N. samples in .fam file: ",nrow(infam)))
print (paste0("N. samples in annotation file: ",nrow(inann)))
m <- merge(infam,inann, by.x="V1", by.y="ID")
try(if(nrow(m) != nrow(infam)) stop("Not all the samples in the .fam file are also in the annotation file"))

# Rename the original .fam file #
system(paste0("cp ",infamD," ",infamD,"_old"))

towrite <- m[,c(1,2,3,4,8,7)]
write.table(towrite,file=infamD,col.names=F,row.names=F,quote=F)

