### PLOTS BY VQSRTranche  ###
### Argument 1: a file containing a tabular form of the variants characteristics (space-separate). This is normally generated by bcftool query.
###             These characteristics are needed: MQ, FS, QD, MQranksum, InbreedingCoeff, FILTER.
### Argument 2: Directory location where the plots should be saved 

library(ggplot2)
library(data.table)
options(warn=-1)

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}


# Read arguments #
args <- commandArgs(trailingOnly = TRUE)
inD = as.character(args[1])
outD = as.character(args[2])
NIND = as.numeric(args[3])

#inD="/humgen/atgu1/fs03/wip/aganna/fin_seq/processed/seq/temp/INFO_G77318RH.txt"
#outD="/humgen/atgu1/fs03/wip/aganna/fin_seq/results/plots/"
#NIND=597

# Read data
dnames <- read.table(inD, header=F, comment.char = "&",nrows=1, stringsAsFactor=F)
a <- strsplit(as.character(dnames[1,]),"]")

print("Reading data")
d1 <- fread(inD, header=F, stringsAsFactor=F)

colnames(d1) <- sapply(a[2:length(a)],"[[",2)



print("Structuring data")

d11 <- d1[d1$FILTER=="PASS",]
d12 <- d1[d1$FILTER%in%c("VQSRTrancheINDEL99.90to100.00","VQSRTrancheSNP99.90to100.00"),]
d13 <- d1[d1$FILTER%in%c("VQSRTrancheINDEL99.80to99.90","VQSRTrancheSNP99.80to99.90"),]
d14 <- d1[d1$FILTER%in%c("VQSRTrancheINDEL99.70to99.80","VQSRTrancheSNP99.70to99.80"),]

newdata1 <- data.frame( FS=as.numeric(d11$FS), QD=as.numeric(d11$QD), MQranksum=as.numeric(d11$MQRankSum), imbcoef=as.numeric(d11$InbreedingCoeff), group=factor(d11$FILTER), DP=d11$DP/NIND, ReadPosRankSum=as.numeric(d11$ReadPosRankSum))
newdata2 <- data.frame( FS=as.numeric(d12$FS), QD=as.numeric(d12$QD), MQranksum=as.numeric(d12$MQRankSum), imbcoef=as.numeric(d12$InbreedingCoeff), group=factor(d12$FILTER), DP=d12$DP/NIND, ReadPosRankSum=as.numeric(d12$ReadPosRankSum))
newdata3 <- data.frame( FS=as.numeric(d13$FS), QD=as.numeric(d13$QD), MQranksum=as.numeric(d13$MQRankSum), imbcoef=as.numeric(d13$InbreedingCoeff), group=factor(d13$FILTER), DP=d13$DP/NIND, ReadPosRankSum=as.numeric(d13$ReadPosRankSum))
newdata4 <- data.frame( FS=as.numeric(d14$FS), QD=as.numeric(d14$QD), MQranksum=as.numeric(d14$MQRankSum), imbcoef=as.numeric(d14$InbreedingCoeff), group=factor(d14$FILTER), DP=d14$DP/NIND, ReadPosRankSum=as.numeric(d14$ReadPosRankSum))


print("Now plotting")

png(paste0(outD,"ReadPosRankSum_by_VQSRTranche.png"), width=1200, height=800, type="cairo")

p1 <- ggplot(aes(x = ReadPosRankSum), data=newdata1) + geom_histogram(aes(fill=group)) +xlab("ReadPosRankSum") + ylab("Number") + ggtitle("ReadPosRankSum by VQSRTranche") 

p2 <- ggplot(aes(x = ReadPosRankSum), data=newdata2) + geom_histogram(aes(fill=group)) +xlab("ReadPosRankSum") + ylab("Number") + ggtitle("ReadPosRankSum by VQSRTranche") 

p3 <- ggplot(aes(x = ReadPosRankSum), data=newdata3) + geom_histogram(aes(fill=group)) +xlab("ReadPosRankSum") + ylab("Number") + ggtitle("ReadPosRankSum by VQSRTranche") 

p4 <- ggplot(aes(x = ReadPosRankSum), data=newdata4) + geom_histogram(aes(fill=group)) +xlab("ReadPosRankSum") + ylab("Number") + ggtitle("ReadPosRankSum by VQSRTranche") 

multiplot(p1,p3,p4,p2, cols=2)

dev.off()


png(paste0(outD,"FS_by_VQSRTranche.png"), width=1200, height=800, type="cairo")

p1 <- ggplot(aes(x = FS), data=newdata1) + geom_histogram(aes(fill=group)) +xlab("FS (truncated 300)") + ylab("Number") + ggtitle("FS by VQSRTranche")  + xlim(c(0,300))

p2 <- ggplot(aes(x = FS), data=newdata2) + geom_histogram(aes(fill=group)) +xlab("FS (truncated 300)") + ylab("Number") + ggtitle("FS by VQSRTranche")  + xlim(c(0,300))

p3 <- ggplot(aes(x = FS), data=newdata3) + geom_histogram(aes(fill=group)) +xlab("FS (truncated 300)") + ylab("Number") + ggtitle("FS by VQSRTranche")  + xlim(c(0,300))

p4 <- ggplot(aes(x = FS), data=newdata4) + geom_histogram(aes(fill=group)) +xlab("FS (truncated 300)") + ylab("Number") + ggtitle("FS by VQSRTranche")  + xlim(c(0,300))

multiplot(p1,p3,p4,p2, cols=2)


dev.off()


png(paste0(outD,"QD_by_VQSRTranche.png"), width=1200, height=800, type="cairo")

p1 <- ggplot(aes(x = QD), data=newdata1) + geom_histogram(aes(fill=group)) +xlab("QD") + ylab("Number") + ggtitle("QD by VQSRTranche")

p2 <- ggplot(aes(x = QD), data=newdata2) + geom_histogram(aes(fill=group)) +xlab("QD") + ylab("Number") + ggtitle("QD by VQSRTranche")  

p3 <- ggplot(aes(x = QD), data=newdata3) + geom_histogram(aes(fill=group)) +xlab("QD") + ylab("Number") + ggtitle("QD by VQSRTranche")  

p4 <- ggplot(aes(x = QD), data=newdata4) + geom_histogram(aes(fill=group)) +xlab("QD") + ylab("Number") + ggtitle("QD by VQSRTranche")  

multiplot(p1,p3,p4,p2, cols=2)

dev.off()


png(paste0(outD,"MQranksum_by_VQSRTranche.png"), width=1200, height=800, type="cairo")

p1 <- ggplot(aes(x = MQranksum), data=newdata1) + geom_histogram(aes(fill=group)) +xlab("MQranksum") + ylab("Number") + ggtitle("MQranksum by VQSRTranche")

p2 <- ggplot(aes(x = MQranksum), data=newdata2) + geom_histogram(aes(fill=group)) +xlab("MQranksum") + ylab("Number") + ggtitle("MQranksum by VQSRTranche")  

p3 <- ggplot(aes(x = MQranksum), data=newdata3) + geom_histogram(aes(fill=group)) +xlab("MQranksum") + ylab("Number") + ggtitle("MQranksum by VQSRTranche")  

p4 <- ggplot(aes(x = MQranksum), data=newdata4) + geom_histogram(aes(fill=group)) +xlab("MQranksum") + ylab("Number") + ggtitle("MQranksum by VQSRTranche")  

multiplot(p1,p3,p4,p2, cols=2)

dev.off()



png(paste0(outD,"inbcoef_by_VQSRTranche.png"), width=1200, height=800, type="cairo")


p1 <- ggplot(aes(x = imbcoef), data=newdata1) + geom_histogram(aes(fill=group)) +xlab("Inbreeding Coef") + ylab("Number") + ggtitle("Inbreeding Coef by VQSRTranche")

p2 <- ggplot(aes(x = imbcoef), data=newdata2) + geom_histogram(aes(fill=group)) +xlab("Inbreeding Coef") + ylab("Number") + ggtitle("Inbreeding Coef by VQSRTranche")  

p3 <- ggplot(aes(x = imbcoef), data=newdata3) + geom_histogram(aes(fill=group)) +xlab("Inbreeding Coef") + ylab("Number") + ggtitle("Inbreeding Coef by VQSRTranche")  

p4 <- ggplot(aes(x = imbcoef), data=newdata4) + geom_histogram(aes(fill=group)) +xlab("Inbreeding Coef") + ylab("Number") + ggtitle("Inbreeding Coef by VQSRTranche")  

multiplot(p1,p3,p4,p2, cols=2)

dev.off()



png(paste0(outD,"DP_by_VQSRTranche.png"), width=1200, height=800, type="cairo")


p1 <- ggplot(aes(x = DP), data=newdata1) + geom_histogram(aes(fill=group)) +xlab("DP") + ylab("Number") + ggtitle("DP by VQSRTranche")

p2 <- ggplot(aes(x = DP), data=newdata2) + geom_histogram(aes(fill=group)) +xlab("DP") + ylab("Number") + ggtitle("DP Coef by VQSRTranche")  

p3 <- ggplot(aes(x = DP), data=newdata3) + geom_histogram(aes(fill=group)) +xlab("DP") + ylab("Number") + ggtitle("DP Coef by VQSRTranche")  

p4 <- ggplot(aes(x = DP), data=newdata4) + geom_histogram(aes(fill=group)) +xlab("DP") + ylab("Number") + ggtitle("DP by VQSRTranche")  

multiplot(p1,p3,p4,p2, cols=2)

dev.off()


png(paste0(outD,"inbcoef_by_VQSRTranche.png"), width=1200, height=800, type="cairo")


p1 <- ggplot(aes(x = imbcoef), data=newdata1) + geom_histogram(aes(fill=group)) +xlab("Inbreeding Coef") + ylab("Number") + ggtitle("Inbreeding Coef by VQSRTranche")

p2 <- ggplot(aes(x = imbcoef), data=newdata2) + geom_histogram(aes(fill=group)) +xlab("Inbreeding Coef") + ylab("Number") + ggtitle("Inbreeding Coef by VQSRTranche")  

p3 <- ggplot(aes(x = imbcoef), data=newdata3) + geom_histogram(aes(fill=group)) +xlab("Inbreeding Coef") + ylab("Number") + ggtitle("Inbreeding Coef by VQSRTranche")  

p4 <- ggplot(aes(x = imbcoef), data=newdata4) + geom_histogram(aes(fill=group)) +xlab("Inbreeding Coef") + ylab("Number") + ggtitle("Inbreeding Coef by VQSRTranche")  

multiplot(p1,p3,p4,p2, cols=2)

dev.off()