### PLOT STAT CONCORDANCE CHIP-WGS ###
### Argument 1: the concordance files (molten format) generated by GATK concordance tool. Each file read contains different results according to DP filter DP=seq(5,40,5).
### Argument 2: Directory location where the plots should be saved 

library(ggplot2)
options(warn=-1)

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}


# Read arguments #
args <- commandArgs(trailingOnly = TRUE)
inD = as.character(args[1])
outD = as.character(args[2])

#inD="/humgen/atgu1/fs03/wip/aganna/fin_seq/processed/psych/concordance"
#outD="/humgen/atgu1/fs03/wip/aganna/fin_seq/results/plots/"
# Read data

conco <- function(file)
{
	newdataF <- NULL
	for (k in seq(5,40,5))
	{
		d <- read.table(paste0(file,"_DP_",k,".txt"), blank.lines.skip = F, skip=3, header=T, stringsAsFactor=F)

		start <- which(d$Sample=="Sample")[1]
		end <- which(d$Sample=="Sample")[2]

		dsel <- d[(start+1):(end-4),]
		dsel2 <- dsel[dsel$Sample!="ALL" & !dsel$Eval_Genotype%in%c("UNAVAILABLE","MIXED","Mismatching_Alleles","NO_CALL") & !dsel$Comp_Genotype%in%c("UNAVAILABLE","MIXED","Mismatching_Alleles","NO_CALL"),]


		ConcHET <- NULL
		ConcHOMVAR <- NULL
		Non_ref_sens <- NULL
		Non_ref_disc <- NULL
		id <- NULL
		for (i in unique(dsel2$Sample))
		{
		  dseT <- dsel2[dsel2$Sample==i,]
		  den <- sum(as.numeric(dseT$Proportion))
		  concHET <- as.numeric(dseT$Proportion[dseT$Comp_Genotype=="HET" & dseT$Eval_Genotype=="HET"]) / sum(as.numeric(dseT$Proportion[dseT$Comp_Genotype=="HET"]))

		  concHOMVAR <- as.numeric(dseT$Proportion[dseT$Comp_Genotype=="HOM_VAR" & dseT$Eval_Genotype=="HOM_VAR"]) / sum(as.numeric(dseT$Proportion[dseT$Comp_Genotype=="HOM_VAR"]))

		  non_ref_sens <- (as.numeric(dseT$Proportion[dseT$Comp_Genotype=="HOM_VAR" & dseT$Eval_Genotype=="HOM_VAR"]) +  as.numeric(dseT$Proportion[dseT$Comp_Genotype=="HET" & dseT$Eval_Genotype=="HET"])) / sum(as.numeric(dseT$Proportion[dseT$Comp_Genotype=="HOM_VAR" | dseT$Comp_Genotype=="HET"]))

		  non_ref_disc <-  sum(as.numeric(dseT$Proportion[!(dseT$Comp_Genotype=="HOM_REF" & dseT$Eval_Genotype=="HOM_REF") & !(dseT$Comp_Genotype=="NO_CALL" | dseT$Eval_Genotype=="NO_CALL") & !(dseT$Comp_Genotype=="HOM_VAR" & dseT$Eval_Genotype=="HOM_VAR") & !(dseT$Comp_Genotype=="HET" & dseT$Eval_Genotype=="HET")])) /
		  sum(as.numeric(dseT$Proportion[!(dseT$Comp_Genotype=="HOM_REF" & dseT$Eval_Genotype=="HOM_REF") & !(dseT$Comp_Genotype=="NO_CALL" | dseT$Eval_Genotype=="NO_CALL")]))

		  ConcHET <- c(ConcHET,concHET)
		  ConcHOMVAR <- c(ConcHOMVAR,concHOMVAR)
		  Non_ref_sens <- c(Non_ref_sens,non_ref_sens)
		  Non_ref_disc <- c(Non_ref_disc,non_ref_disc)
		  id <- c(id,i)
		  newdata <- data.frame(ID=id,ConcHET=ConcHET,ConcHOMVAR=ConcHOMVAR,Non_ref_sens=Non_ref_sens,Non_ref_disc=Non_ref_disc,DP=k)
		}
	newdataF <- rbind(newdataF,newdata)
	}
	return(newdataF)
}


newdata1 <- conco(paste0(inD,"_SNP_EX"))
newdata2 <- conco(paste0(inD,"_SNP_WG"))

newdata1 <- newdata1[!is.na(newdata1$Non_ref_sens) & !is.na(newdata1$Non_ref_disc),]
newdata2 <- newdata2[!is.na(newdata2$Non_ref_sens) & !is.na(newdata2$Non_ref_disc),]


mead11 <- aggregate(newdata1$Non_ref_sens,list(newdata1$DP),median,na.rm=T) 
mead12 <- aggregate(newdata1$Non_ref_disc,list(newdata1$DP),median,na.rm=T)

mead21 <- aggregate(newdata2$Non_ref_sens,list(newdata2$DP),median,na.rm=T)
mead22 <- aggregate(newdata2$Non_ref_disc,list(newdata2$DP),median,na.rm=T)


png(paste0(outD,"concordance_WG_chip_by_DP.png"), width=1200, height=800, type="cairo")
p1 <- ggplot(aes(y=Non_ref_sens,x=DP),data=newdata1) + geom_line(aes(group=ID), alpha=0.5, colour="red") + xlab("DP < x") +ylab("Non-reference sensitivity")  + geom_line(aes(y=x,x=Group.1),data=mead11,colour="blue", lwd=2) + ggtitle("SNPs - EXOME")
p2 <- ggplot(aes(y=Non_ref_disc,x=DP),data=newdata1) + geom_line(aes(group=ID), alpha=0.5, colour="black") + xlab("DP < x") +ylab("Non-reference discrepancy") + geom_line(aes(y=x,x=Group.1),data=mead12,colour="blue", lwd=2) 

p3 <- ggplot(aes(y=Non_ref_sens,x=DP),data=newdata2) + geom_line(aes(group=ID), alpha=0.5, colour="red") + xlab("DP < x") +ylab("Non-reference sensitivity")  + geom_line(aes(y=x,x=Group.1),data=mead21,colour="blue", lwd=2) + ggtitle("SNPs - WG")
p4 <- ggplot(aes(y=Non_ref_disc,x=DP),data=newdata2) + geom_line(aes(group=ID), alpha=0.5, colour="black") + xlab("DP < x") +ylab("Non-reference discrepancy")  + geom_line(aes(y=x,x=Group.1),data=mead22,colour="blue", lwd=2) 

multiplot(p1,p2, p3, p4, cols=2)
dev.off()



